site_name: Brown Water Python
pages:
  - Home: index.md
  - Intro: intro.md
  - Alternatives: alternatives.md

markdown_extensions:
  - meta
  - toc
  - tables
  - pymdownx.superfences
  - pymdownx.highlight
  - footnotes
